version: '3.8'

services:
  web:
    build: .
    container_name: php_apache
    volumes:
      - ./src:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: kantaki_dev
      MYSQL_USER: kantaki
      MYSQL_PASSWORD: kantaki
    ports:
      - "3306:3306"

volumes:
  db_data:
